
server:
  port: 8081

##---------------------------------After Route Predicate Factory---------------------------
#spring:
#  profiles:
#    active: after_route
#
### ---  相当于另外一个文件的配置，可以使用重复的参数 如 此处的 spring:
### -  表示集合形式
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: after_route
#          uri: http://httpbin.org:80/get
#          ##意思是 请求时间在下面时间之后的才能通过
#          predicates:
#            - After=2017-11-20T17:42:47.789-07:00[America/Denver]
#  profiles: after_route

##--------------------------------Header Route Predicate Factory----------------------------
##在下面的配置中，当请求的Header中有X-Request-Id的header名，且header值为数字时，请求会被路由到配置的 uri
## 命令  $ curl -H 'X-Request-Id:1' localhost:8081

#pring:
# profiles:
#   active: header_route

#--
#pring:
# cloud:
#   gateway:
#     routes:
#       - id: header_route
#         uri: http://httpbin.org:80/get
#         predicates:
#           - Header=X-Request-Id, \d+
# profiles: header_route

##-------------------------------Cookie Route Predicate Factory-------------------------------
## Cookie Route Predicate Factory需要2个参数，一个时cookie名字，另一个时值，可以为正则表达式。它用于匹配请求中，带有该名称的cookie和cookie匹配正则表达式的请求

#spring:
#  profiles:
#    active: cookie_route
#
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: cookie_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Cookie=name, forezp
#  profiles: cookie_route


##-------------------------------Host Route Predicate Factory----------------------------------
## Host Route Predicate Factory需要一个参数即hostname，它可以使用. * 等去匹配host。这个参数会匹配请求头中的host的值，一致，则请求正确转发


#spring:
#  profiles:
#    active: host_route
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: host_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Host=**.fangzhipeng.com
#  profiles: host_route


##-----------------------------Method Route Predicate Factory----------------------------------------------------

##Method Route Predicate Factory 需要一个参数，即请求的类型。比如GET类型的请求都转发到此路由。在工程的配置文件加上以下的配置：
##在下面的配置中，所有的GET类型的请求都会路由转发到配置的uri。使用 curl命令模拟 get类型的请求，会得到正确的返回结果
##  curl localhost:8081   返回正确
##  curl -XPOST localhost:8081    模拟post  返回失败
#spring:
#  profiles:
#    active: method_route
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: method_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Method=GET
#  profiles: method_route
#
#
##-----------------------------Path Route Predicate Factory---------------------------------------------------------
## 这个一直404，没有试成功


spring:
  profiles:
    active: path_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://httpbin.org:80/get
          predicates:
            - Path=/foo/{segment}
  profiles: path_route

##------------------------------Query Route Predicate Factory--------------------------------------------------------
# 在上面的配置文件中，配置了请求中含有参数foo，并且foo的值匹配ba.，则请求命中路由，比如一个请求中含有参数名为foo，值的为bar，能够被正确路由转发

#spring:
#  profiles:
#    active: query_route
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: query_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Query=foo, ba.
#  profiles: query_route


# Query Route Predicate Factory也可以只填一个参数，填一个参数时，则只匹配参数名，即请求的参数中含有配置的参数名，则命中路由。
#  比如以下的配置中，配置了请求参数中含有参数名为foo 的参数将会被请求转发到uri为http://httpbin.org:80/get
#spring:
#   profiles:
#     active: query_route
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: query_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Query=foo
#  profiles: query_route



