
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
  ## 使用zipkin 进行链式调用追踪
  zipkin:
    base-url: http://localhost:9411

zuul:
  routes:
    api-a:
      path: /api-a/*
      serviceId: service-ribbon
    api-b:
      path: /api-b/*
      serviceId: service-feign