
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  # 心跳检测检测与续约时间
  # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  # lease-renewal-interval-in-seconds 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
  # lease-expiration-duration-in-seconds  告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

server:
  port: 8770
  tomcat:
    #解决http响应数据中文乱码问题  第一步
    uri-encoding: UTF-8
spring:
  application:
    name: config-server2
  cloud:
    config:
      label: master  #配置仓库分支
      profiles:
        active: git #设置使用本地配置(默认是git,可以设置：subversion(SVN)，native(本地))
      server:
        git:
          uri: https://github.com/fengxue530/springCloudDemoMe   # 配置git仓库地址
          search-paths: config/testrepo                           #配置文件所在的目录
          #username:     开放项目不需要
          #password:

  #解决http响应数据中文乱码问题 第二步
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
