eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
  ## 使用zipkin 进行链式调用追踪
  zipkin:
    base-url: http://localhost:9411

#Feign是自带断路器的，在D版本的Spring Cloud中，它没有默认打开。需要在配置文件中配置打开它
feign:
  hystrix:
    enabled: true

